# Generated by Django 5.2 on 2025-08-11 07:01

import django.core.validators
import users.models
import users.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('desarrollo_web', 'Desarrollo Web'), ('ciberseguridad', 'Ciberseguridad'), ('ia', 'Inteligencia Artificial')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.Usuario.user_directory_path, validators=[users.validations.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ingreso',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('12+', '12+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="La matrícula debe comenzar con la letra 'E'.", regex='^E')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
