# Generated by Django 5.2 on 2025-05-13 09:12

import expediente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=expediente.models.user_document_path),
        ),
    ]
