# Generated by Django 5.2 on 2025-06-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('nombre_proyecto', models.CharField(max_length=500)),
                ('objetivo', models.TextField()),
                ('justificacion', models.TextField()),
                ('problema', models.TextField()),
                ('actividades', models.TextField()),
                ('stack', models.TextField()),
                ('modalidad', models.CharField(choices=[('virtual', 'Virtual'), ('hibrido', 'Híbrido'), ('presencial', 'Presencial')], max_length=15)),
                ('tipo_entidad', models.CharField(choices=[('empresa', 'Empresa'), ('institucion', 'Institución')], max_length=20)),
                ('nombre_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('giro', models.CharField(blank=True, choices=[('servicios', 'Servicios'), ('manufactura', 'Manufactura'), ('comercial', 'Comercial')], max_length=20, null=True)),
                ('pagina_web', models.URLField(blank=True, null=True)),
                ('numero_estudiantes', models.PositiveIntegerField(blank=True, null=True)),
                ('especialidad', models.CharField(blank=True, choices=[('ciberseguridad', 'Ciberseguridad'), ('ia', 'Inteligencia Artificial'), ('web', 'Desarrollo Web')], max_length=30, null=True)),
                ('periodo', models.CharField(blank=True, choices=[('enero-junio', 'Enero - Junio'), ('agosto-diciembre', 'Agosto - Diciembre')], max_length=30, null=True)),
                ('competencias', models.TextField(blank=True, null=True)),
                ('apoyo', models.BooleanField(default=False)),
                ('tipo_apoyo', models.TextField(blank=True, null=True)),
                ('estudiante_interesado', models.BooleanField(default=False)),
                ('nombre_estudiante_solicitado', models.CharField(blank=True, max_length=255, null=True)),
                ('es_tec', models.BooleanField(blank=True, null=True)),
                ('incluir_asesor', models.BooleanField(blank=True, null=True)),
                ('nombre_asesor', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos_imagenes/')),
                ('fecha_subida', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
