# Generated by Django 5.2 on 2025-06-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioproyecto',
            name='competencias',
        ),
        migrations.RemoveField(
            model_name='formularioproyecto',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='formularioproyecto',
            name='estudiante_interesado',
        ),
        migrations.RemoveField(
            model_name='formularioproyecto',
            name='incluir_asesor',
        ),
        migrations.RemoveField(
            model_name='formularioproyecto',
            name='nombre_asesor',
        ),
        migrations.RemoveField(
            model_name='formularioproyecto',
            name='nombre_estudiante_solicitado',
        ),
        migrations.RemoveField(
            model_name='formularioproyecto',
            name='stack',
        ),
        migrations.AddField(
            model_name='formularioproyecto',
            name='nombre_institucion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formularioproyecto',
            name='giro',
            field=models.CharField(blank=True, choices=[('diseño', 'Diseño'), ('manufactura', 'Manufactura'), ('mantenimiento', 'Mantenimiento'), ('automatizacion', 'Automatización'), ('energias', 'Energías Renovables'), ('aire_acond', 'Aiure acondicionado y refrigeración'), ('mecanica_auto', 'Mecanica Automotriz'), ('investigacion', 'Investigación'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formularioproyecto',
            name='numero_estudiantes',
            field=models.CharField(blank=True, choices=[('uno', '1'), ('dos', '2')], max_length=3, null=True),
        ),
    ]
