# Generated by Django 5.2 on 2025-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0003_remove_formularioproyecto_competencias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioproyecto',
            name='actividades',
        ),
        migrations.AlterField(
            model_name='formularioproyecto',
            name='apoyo',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formularioproyecto',
            name='es_tec',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
