# Generated by Django 5.2 on 2025-08-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0004_remove_formularioproyecto_actividades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioproyecto',
            name='numero_estudiantes',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], null=True),
        ),
    ]
