# Generated by Django 5.2 on 2025-11-17 22:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0005_alter_formularioproyecto_numero_estudiantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionproyecto',
            options={'ordering': ['-fecha_aplicacion'], 'verbose_name': 'Aplicación a Proyecto', 'verbose_name_plural': 'Aplicaciones a Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='formularioproyecto',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='aplicacionproyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='formularioproyecto',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('sistemas', 'Sistemas Computacionales'), ('industrial', 'Ingeniería Industrial'), ('gestion', 'Ingeniería en Gestión Empresarial'), ('mecanica', 'Ingeniería Mecánica'), ('mecatronica', 'Ingeniería Mecatrónica'), ('electronica', 'Ingeniería Electrónica'), ('electrica', 'Ingeniería Eléctrica'), ('civil', 'Ingeniería Civil')], max_length=20, null=True, verbose_name='Especialidad requerida'),
        ),
        migrations.AddField(
            model_name='formularioproyecto',
            name='estudiante_interesado',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formularioproyecto',
            name='nombre_estudiante_solicitado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aplicacionproyecto',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aplicacionproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='banco_proyectos.formularioproyecto'),
        ),
        migrations.AlterField(
            model_name='formularioproyecto',
            name='giro',
            field=models.CharField(blank=True, choices=[('diseño', 'Diseño'), ('manufactura', 'Manufactura'), ('mantenimiento', 'Mantenimiento'), ('automatizacion', 'Automatización'), ('energias', 'Energías Renovables'), ('aire_acond', 'Aire acondicionado y refrigeración'), ('mecanica_auto', 'Mecánica Automotriz'), ('investigacion', 'Investigación'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formularioproyecto',
            name='numero_estudiantes',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacionproyecto',
            unique_together={('alumno', 'proyecto')},
        ),
    ]
