# Generated by Django 5.2 on 2025-11-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0006_alter_aplicacionproyecto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacionproyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado_por_empresa', 'Aceptado por Empresa'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=30),
        ),
    ]
