# Generated by Django 5.2 on 2025-11-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0007_alter_aplicacionproyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioproyecto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('terminado', 'Terminado')], default='activo', max_length=20, verbose_name='Estado del Proyecto'),
        ),
        migrations.AddField(
            model_name='formularioproyecto',
            name='fecha_terminado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Terminación'),
        ),
    ]
